### ISSUE TITLE
make Solver::run not a trait implementation

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#11]
This does bring up the related issue that `Solver::run` is a trait implementation, so theoretically someone could  

```rust
impl<P: Package, V: Version + Hash> Solver<P, V> for BadSolver<P, V> {
    fn list_available_versions(&mut self, package: &P) -> Result<Vec<V>, Box<dyn Error>> {
        ...
    }

    fn get_dependencies(
        &mut self,
        package: &P,
        version: &V,
    ) -> Result<Option<Map<P, Range<V>>>, Box<dyn Error>> {
        ...
    }

    fn run(
        &mut self,
        package: P,
        version: impl Into<V>
    ) -> Result<Map<P, V>, PubGrubError<P, V>> {
        Ok(Map::new())
    }
}
```

I don't know why someone would, but our api lets them. Mabe `run` could be a free function that takes a `impl Solver` as an argument, or a method on anything that impls `Solver`.

_Originally posted by @Eh2406 in https://github.com/mpizenberg/pubgrub-rs/issues/10#issuecomment-703261551_

**Comment by mpizenberg** [comment]
In the case `Solver::run` is detached from the `Solver` trait, maybe that one should be renamed something like `Retriever` or `Fetcher` or something more adequate.

**Comment by aleksator** [comment]
I actually was surprised by that being a trait implementation as well, because in my mind (and previous implementation attempts) `run()` was a separate function. I had not come up with any downsides though like @Eh2406 did, so I hadn't commented.

I'll get to work on separating it.

**Comment by mpizenberg** [comment]
Also closing this in favor of #15
