### ISSUE TITLE
More compatible error type

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#116]
At a minimum we should switch to `dyn Error + Send + Sync` to be compatible with `anyhow`. Even better would be to have an arbitrary type associated with a dependency provider that we return in our errors. We don't actually care what the properties of a user's error are, we just need to be able to return them to the user.

https://rust-lang.zulipchat.com/#narrow/stream/260232-t-cargo.2FPubGrub/topic/Error.20type

**Comment by charliermarsh** [comment]
@Eh2406 - Are you open to a PR changing to `dyn Error + Send + Sync`?

**Comment by Eh2406** [comment]
I think a fully generic type would be better, but let's not let the perfect be the enemy of good. Yes I would accept such a PR.
