### ISSUE TITLE
Move to edition 2021

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#140]

**Comment by 0xAtticus** [comment]
I would like to work on it if that's possible.
@Eh2406 I created PR #142  , but I was expecting more things to do. Am I missing something ?

**Comment by Eh2406** [comment]
It is entirely possible that no other code changes required. To check, could you look through the addition guide at https://doc.rust-lang.org/edition-guide/rust-2021/index.html . For each thing that changed check whether it's relevant to our code base. If it is fix are code to the new idiom, if not comment on your PR why that change wasn't relevant.

Sorry, I should've put that description in this issue before I marked it good first issue.
