### ISSUE TITLE
Dependency version with invalid direct dependencies should be tracked as incompatibility

### ISSUE THREAD

**Issue by zanieb** [pubgrub-rs/pubgrub#151]
Example at https://github.com/zanieb/pubgrub/blob/zanie/examples/examples/unsat_indirect_dependency_conflict_backtrack.rs

Given the following situation:

- root depends on foo
- foo 1.1 depends on bar 1.0
- foo 1.2 depends on bar 1.0 and bar 2.0 (invalid)

The solver fails with an empty dependency set on foo 1.2.
Instead, the solver should mark foo 1.2 as incompatible(?) and backtrack to a valid version of foo such as 1.1.

**Comment by zanieb** [comment]
In general, we need to be able to indicate that some package version does not have valid dependencies and should be ignored with a custom message for reports. I opened https://github.com/pubgrub-rs/pubgrub/issues/152 to track that.

**Comment by Eh2406** [comment]
> The solver fails with an empty dependency set on foo 1.2.

Is this the DependencyOnTheEmptySet error? There is discussion about removing it in https://github.com/pubgrub-rs/pubgrub/issues/125 and it was removed in #133, please try the `dev` branch and let me know if it's still a problem.

**Comment by zanieb** [comment]
Ah thank you — I misunderstood the main branch in this project and have rebased my examples onto the `dev` branch.

This example indeed solves with `dev`.
