### ISSUE TITLE
Clickable documentation links

### ISSUE THREAD

**Issue by aleksator** [pubgrub-rs/pubgrub#17]
Use rustdoc syntax to produce clickable links in the documentation where possible.

For example, [Version] instead of \`Version\` if the linked item is in the same module.
If the link wants to reference item from a different module, a path has to provided:
`[Version](crate::version::Version)`.

Open question:
Is it possible to automatically test that created links are valid?

**Comment by mpizenberg** [comment]
Seems like a very good improvement! I know of a tool in elm land called elm-review that can do this kind of things I believe, but don't know on rust land sorry ^^

**Comment by aleksator** [comment]
Actually `cargo doc` emits warnings if some links are broken. We can set up CI pass to check for them!

**Comment by aleksator** [comment]
Fixed by #26. CI changes were left for another PR.
