### ISSUE TITLE
Pick packages with a heuristic

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#20]
Cargo and the Dart implementation have an optimization where if it is not clear which package to make a decision on it picks the one with the fewest options. We do not yet have that implomented, it could go https://github.com/mpizenberg/pubgrub-rs/blob/f1608ecf2deee92550aa56693c1a97113a8584c9/src/internal/partial_solution.rs#L94. A good heuristics can make a huge difference here. It is not clear how to thread the data thure, but we should do something.

**Comment by mpizenberg** [comment]
Yeah it might force us to precompute the intersection of all derivations in the partial solution, so it might also change a few other places where we have to compute that.

**Comment by mpizenberg** [comment]
It also requires to have the actual list of potential packages, which is not necessary for now since we just pick the first item of the iterator, so it stops evaluation of potential packages when one is found.

**Comment by Eh2406** [comment]
using the dumbest huristick:
```rust
    pub fn pick_package(
        &self,
        dependency_provider: &impl DependencyProvider<P, V>,
    ) -> Option<(P, Term<V>)> {
        self.memory
            .potential_packages()
            .min_by_key(|(p, _)| {
                dependency_provider
                    .list_available_versions(p)
                    .unwrap() // TODO: remove this!
                    .len() // TODO: should be len that matches
            })
            .map(|(p, all_terms)| (p.clone(), Term::intersect_all(all_terms.iter())))
    }
```
Brings the benchmark from .282 sec/iter to .081 sec/iter. So this is definitely worth pursuing.

**Comment by mpizenberg** [comment]
ahah optimization season is open ^^

**Comment by mpizenberg** [comment]
I've replaced back our deterministic hashmap by the default one just to have random order as a strategy. Then running many runs may provide good statistical insight. Having the standard deviation and min/max duration would provid very useful info about what an optimal or a bad strategy might look like performance-wise. Here I get more or less the following results:

```txt
test large_case ... bench:  56,593,558 ns/iter (+/- 43,373,689)
```

I'm not sure what the number in parenthesis is, but if it is the standard deviation, it means that there are indeed wild differences induced by the order of packages. It also gives a rough idea of the types of gains that a very good heuristic might provide. Being able to increase the number of runs could be very useful to get that statistical information. Maybe criterion provides that kind of settings?

**Comment by Eh2406** [comment]
I think it is `(max - min) / 2` (std's benchmarking has its odditties). With how well #32 seam to work it may be worth moving this benchmark to Criterion for exactly the kinds of controls you describe. And it is time to use #28 to make a new bigger benchmark. :-)
