### ISSUE TITLE
CI is failing on dev.

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#218]
We have recently successfully merged PR's that failed "Commit messages follow project guidelines" CI.

1. https://github.com/pubgrub-rs/pubgrub/actions/runs/8914690905/job/24482780384
2. https://github.com/pubgrub-rs/pubgrub/actions/runs/8926571377/job/24517897487
3. https://github.com/pubgrub-rs/pubgrub/actions/runs/8973450833/job/24643647093

We should either give up on this check. Or fix CI (do not let them merge) and reset the dev branch (do not have them in the history) and reemerged the PR's.

**Comment by konstin** [comment]
Personally, i don't think it adds value, but I'm not opposed to having it. We should change it though to run directly when you put the PR up instead of later as it used to.

**Comment by Eh2406** [comment]
> Personally, i don't think it adds value, but I'm not opposed to having it. 

Same

> We should change it though to run directly when you put the PR up instead of later as it used to.

I found that very annoying because CI would basically always be ❌, especially annoying when the commits it was mad about where going to get squashed away.

I am very troubled that CI let things merge after finding ❌. Why did that happen and what else got through?
