### ISSUE TITLE
Crazy Entity Component System (ECS) idea

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#22]
Let first acknowledge that I know nothing about all that follows and that this is mostly a crazy idea induced by extended excitement that I needed to get out of my head. As such I'll close this issue just after opening it.

I've heard a lot of good things in game dev about ECS for flexible and efficient (thanks to data locality) modelization of game mechanics. Aaaand, if you squint a lot, we have a ~game~ loop, ~entities~ data (assignments and incompatibilities) and ~components~ processing units (conflict resolution, unit propagation)? 

That may be very far fetched, and not practical, and actually not correct since I don't know a thing about ECS except the vague concept, but hey, any idea can be useful right?

**Comment by harrysarson** [comment]
Maybe interesting link about ECS for an alogrithm: https://ferrous-systems.com/blog/dlx-in-rust/
