### ISSUE TITLE
feat: let the dependency provider choose a package

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#40]
We already let the `DependencyProvider` the responsibility of ordering versions by preference. This gives a great deal of flexibility since the provider can then change that order to implement multiple strategies such as newest versions first, oldest versions first, locked versions first, stored on file system versions first etc.

Recently, we have been discussing how to improve the performance of solver by smartly picking the next package to evaluate #32. It has been a very good improvement, but I can't stop but wonder if that should be our choice. I don't think so. And just like with versions, giving that choice back to the `DependencyProvider` would bring more flexibility I think. For correctness, we still need to pre-select the `potential` packages, but once that's done, we could let the `DependencyProvider` decide which one to choose from a provided iterator of potential packages. Having the precomputed term intersection provided by the solver as in #37 would even result in cleaner code since the `partial_solution` doesn't need to call `list_available_versions` anymore, the `DependencyProvider` can do that on its own however it wants to do it.

**Comment by Eh2406** [comment]
So I experimented with adding a `pick_package` that takes a `impl Iterator<Item = (P, Term<V>)>` and returns a `Result<P, `. There is a provided implementation that does fewest versions using `list_available_versions`, but it can be overwritten. For example `OfflineDependencyProvider` can use the same heuristic with many fewer allocations in its impl. This was going great! So time to clean the api, Can we prevent a bad implementation from returning a `P` that is not in the `Iterator`? (Yes) Can we limit how much of `Term`s api we make public? (Yes)

Then I noticed that the only thing we do with the resulting `P` was pass it to `list_available_versions` and the only thing we do with that was take the first in the list. So do we want to make a more radical change to the api by doing away with `list_available_versions` and having `pick_package` return a `Result<(P, V), `?

**Comment by mpizenberg** [comment]
Very interesting!

> So do we want to make a more radical change to the api by doing away with list_available_versions and having pick_package return a Result<(P, V), ?

Regrouping them in one call in the retriever is a good idea! I'd say we should go for it and see how that goes. Since it's referred to as "decision making" in [pubgrub doc](https://github.com/dart-lang/pub/blob/master/doc/solver.md#decision-making), it could be renamed `make_decision` maybe? `pick_package_version` fits well also.

**Comment by mpizenberg** [comment]
It could short-circuit many `unit_propagation` loops where we add `NoVersion(...)` one after the other (especially in the strategy where we pick the package with the lowest number of matching versions) by always picking a pair `(P, V)` where there is at least one `V` match the term. Otherwise it could return a variant like `NoDecisionPossible` and we could add a bunch of `NoVersion(...)` all at once for all potential packages to the incompatibilities before looping back to the next unit propagation. But maybe we could notice that it is faster to fail earlier and there could be a variant like `NoDecisionPossibleForPackages(&[P])` where instead of picking a matching version, it would directly return all packages for which there was no matching version all at once.

A lot of design space to explore!
