### ISSUE TITLE
Large files in the repository

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#43]
Currently, the compressed files stored in the repository amount for 1.3 MB of data. Uncompressed, that data is partly due to the source code of this repository, and partly due to assets such as in the gh-pages branch. To understand the repartition of that data, let's have a look at the uncompressed data in the `gh-pages` and `new-benchmark` branches.

## gh-pages

That branch contains the API docs generated by `cargo doc` that we are publishing on https://pubgrub-rs.github.io/pubgrub/pubgrub/ for people to have a look at the current API docs on the dev branch without having to clone the repo. Removing the `.git/` repository, that data amounts to 2.6 MB.

It is significant compared to text files of the source code. I'd prefer if GitHub would deal with pages the same way Gitlab does, as build artifacts of CI. Unfortunately, it has to be in-tree. For this reason, I've setup the gh-pages action to always reset the `gh-pages` branch as an orphan branch and replace the commit instead of pushing new commits on top.

Another option would be to use an external service for our static pages such as documentation. I've used netlify for a while now and really like them. I see that there are actions to deploy to netlify so we could do that instead: https://github.com/marketplace/actions/netlify-deploy.

## new-benchmark

Currently, the uncompressed data amounts to 460 KB, with 184 KB being the ron example files, so a bit more than a third of it. Those files are only needed when working on optimizations, so not useful for most users and contributors. If we keep gh-pages in tree, this is marginal. If we decide to move pages outside of the repo however, it becomes non-negligible and there are different ways we could deal with it.

First, we could just remove them and share them between each other by messages / emails. _crowd screaming in the back_ Ok well not a very good idea ^^.

Alternatively, we could use a git submodule. This is another repo, which is declared in the dependencies of this repo, so if we clone with the `--recursive` option we get also retrieve the submodules. Managing the files in the submodules is a bit different than in the root repository, but if you are not familiar with git submodules, and if we choose this option at some point, I can give some advice on how to use them easily without having to manage two separate repositories on your file system.
 
Another option is using a git LFS provider. LFS (Large File Storage for git) seems to be the most adequate solution for this since file versions can be tracked (as with submodules) but in a way that is optimized for large files. However, it can be challenging to use correctly on CI, and there is a 1GB monthly bandwidth limit on the free tier in GitHub. That bandwidth can easily be exceeded with multiple forks / clones and CI misconfigurations. So LFS isn't the right fit for us I think.

## Diversity of benchmarks

Whether we choose to move large benchmark files outside of the root repository or not, we should still evaluate if those benchmarks are useful at all. In issue #19, I made an [analysis of the shape of the benchmark data](https://github.com/pubgrub-rs/pubgrub/issues/19#issuecomment-706436619) for the first large index. It revealed for example that the resolution mostly involved generating incompatibilities from dependencies, that there was very few conflicts, and other things I didn't put there such as almost no dependencies could be regrouped (if a:1 depends on b:1, and a:2 depends on b:1, then a:1 union a:2 depends on b:1). It is possible that the two new benchmarks have exactly the same profile, and in such case, only one of the three is actually needed.

Being able to do some analysis of the registries generated by proptest is something that would be great to have before adding new benchmark data to the repository in my opinion.

**Comment by Eh2406** [comment]
I especially love the point about whether any new benchmarks are substantially different than the existing one. I'd much prefer to be optimizing something that runs in 0.03 sec then a comparable program that runs in 0.3 sec. Any analyses or scripts to as assess that would be great!

**Comment by mpizenberg** [comment]
Ok it's clear we want to keep versioned data for benchmarks to a minimal. Especially considering potential serialization changes that can require a new copy of the data in git history. No need to keep this issue open.
