### ISSUE TITLE
In memory, no need to keep derivations when there is a decision

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#56]
I realized that while writing the guide. Every usage of memory we have will either do something if there is a decision or something else if there isn't one yet. The only method returning a mix of decision and derivation is `assignment_intersection` but in fact, if there is a decision, we don't need derivations term, since the intersection will directly be the term of the decision.

So in fact we should have `PackageAssignment` be an enum instead of a struct. That would imply some changes in the API, and especially some algorithm changes regarding `remove_decision` that should not be used anymore, but I believe this is doable.

**Comment by Eh2406** [comment]
That is a grate point. I think it will clean things up a lot. If it does then I'd be for it even if it is a small performance regression.
