### ISSUE TITLE
Conflict resolution improvements

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#57]
Writing the [detailed explanation on conflict resolution](https://github.com/pubgrub-rs/pubgrub/blob/guide/guide/src/internals/conflict_resolution.md) helped me better understand how it works. In particular I think we can improve the conflict resolution code in many ways, including:

1. Avoiding the computation of `self.partial_solution.relation(&root_cause)` after conflict resolution. That also means avoiding one impossible `Failure` case so that's great.
2. Simplify prior cause computation.
3. Doing only one pass instead of two by keeping the decision level of the last assignment that made a term of the incompatibility satisfied.

(1) I now understand that since decision levels of the satisfier and previous satisfier are different, backtracking to the previous decision level implies that only one term will be unsatisfied in the incompatibility, so the incompatibility is guaranteed to be almost satisfied. And we know that the unsatisfied package is the one of the satisfier. So no need to redo that `self.partial_solution.relation(&root_cause)` call after conflict resolution, we can instead return that package term of the incompatibility in the output of conflict resolution.

(2) Currently, when computing prior cause, we are explicitly passing it the term of the derivation. But that term is guaranteed to be the negation of the term corresponding to that package in the `cause` of that derivation. So we can simply remove that from the `prior_cause` method arguments. Then, we can rewrite prior cause as:

```diff
diff --git a/src/internal/incompatibility.rs b/src/internal/incompatibility.rs
index 64c7a20..31a113a 100644
--- a/src/internal/incompatibility.rs
+++ b/src/internal/incompatibility.rs
@@ -207,15 +207,14 @@ impl<P: Package, V: Version> Incompatibility<P, V> {
         satisfier: &Term<V>,
     ) -> Self {
         let kind = Kind::DerivedFrom(incompat.id, satisfier_cause.id);
-        let mut t1 = incompat.package_terms.clone();
-        let mut t2 = satisfier_cause.package_terms.clone();
-        t1.remove(package);
-        t2.remove(package);
-        let mut prior_cause_terms = Self::intersection(&t1, &t2);
-        let term = incompat.package_terms.get(package).unwrap();
-        let p_term = term.union(&satisfier.negate());
-        if p_term != Term::any() {
-            prior_cause_terms.insert(package.clone(), p_term);
+        let mut incompat1 = incompat.package_terms.clone();
+        let mut incompat2 = satisfier_cause.package_terms.clone();
+        let t1 = incompat1.remove(package).unwrap();
+        let t2 = incompat2.remove(package).unwrap();
+        let mut prior_cause_terms = Self::intersection(&incompat1, &incompat2);
+        let term = t1.union(&t2);
+        if term != Term::any() {
+            prior_cause_terms.insert(package.clone(), term);
         }
         Self {
             id,
```

(3) When making progress on the history of assignments, we are keeping track of the terms of the incompatibility that get satisfied. This means that we could record decision levels when those events occur. And when finally getting to the satisfier, comparing its decision level with the one of the last package term to get satisfied. Technically, this would not "exactly" be the previous satisfier, since the actual previous satisfier could correspond to the same package that the satisfier in some cases. But the guarantee of the incompatibility being almost satisfied would still hold! So I'd be super interested to see if that would make the algorithm still work, or if there is some special thing the previous satisfier has, that I didn't fully understand yet.

**Comment by mpizenberg** [comment]
The satisfier and previous satisfier corresponding to the same package seems to be quite frequent with the way we deal with ranges. I've just try a few things to detect it, and both the `conflict_resolution` and `conflict_with_partial_satisfier` examples trigger this. I don't know if the decision level in those cases would be different than the one that the new approach (3) would use but I have a feeling that we will know rather soon if (3) still works.

**Comment by Eh2406** [comment]
I do not understand this stuff well enough yet to have come up with any of these suggestions, but they sound plausible once you suggested them. Look forward to seeing what happens when we give them a try!

**Comment by Eh2406** [comment]
I played with 1 and 2 (progress at https://github.com/pubgrub-rs/pubgrub/compare/dev...conflict_resolution) and it looks really good. I did not figure out the details of 3, by trying to do it. Maybe another day, or maybe when you have time.

**Comment by mpizenberg** [comment]
Thanks for 1 and 2 impl! Let leave 3 for later (after v0.2) because it changes the algorithm and I'd be better to publish an update to the crate with all the recent improvements and fixes which do not introduce new behavior.

**Comment by mpizenberg** [comment]
It seems to me most of the things discussed here are now either implemented or out of date so we can probably close this issue.
