### ISSUE TITLE
Implement TryFrom<&str> for SemanticVersion and Range

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#7]
When using `SemanticVersion` for another project, I need to serialize-deserialize it from strings. It would be nice to have `TryFrom<&str>` that would be the reverse of `Display` for `SemanticVersion` and `Range<V>`.

**Comment by mpizenberg** [comment]
Or rather `FromStr`

**Comment by aleksator** [comment]
Wouldn't be a proper solution to use https://lib.rs/crates/semver-parser for that?

**Comment by mpizenberg** [comment]
> Wouldn't be a proper solution to use https://lib.rs/crates/semver-parser for that?

Maybe? This appears to support all the bells and whistles like `-alpha1` etc. It also depends on pest for parsing since it has to be more rigorous. For my usage at least a very simple implementation of `FromStr` based on `str.split(...)` is perfectly fine.

**Comment by aleksator** [comment]
It must have been a recent addition to use pest, since the last time I checked they used a custom recursive descent parser.
Let me check. Looks like they just added it in the last version, since 0.9 has no dependencies.

Regarding `-alpha1` versions, a support for those would need to be added for the crate to be considered for inclusion in Cargo. Although you might not needed it for your application.
The other things they handle you might want to have though: support for ^, ~ semver syntax, etc.

**Comment by mpizenberg** [comment]
I totally agree that a complete support of semantic versioning is needed for use in cargo. That's why only the `Version` trait is required for the algorithm. In this case, I provided the `SemanticVersion` concrete case as a commodity for systems (like elm versions) that are restricted to what I'd call "strict" semantic versioning, where only `major`, `minor` and `patch` have meaning.

In this specific case, the current `SemanticVersion` type is not suited for additional details like alpha, beta etc modifiers. So in my opinion, the only outcomes that make sense are:
1. remove the `SemanticVersion` type
2. impl `FromStr` simply for the "strict" `SemanticVersion` as defined currently
3. change the `SemanticVersion` type into a more complete one such as the one provided by semver-parser

I lean toward 2 but I can understand any of the other two options.

**Comment by mpizenberg** [comment]
`FromStr` is enough for basic serialization-deserialization needs, so since that's done, we can ask the question for `TryFrom` later when it's needed.

**Comment by mpizenberg** [comment]
Range is slightly more complicated to get right. I'm not de-serializing any kind of `Range` but only those of the type `v1 <= v < v2` anyway so I'm doing a specialized thing for this case in elm-test-rs. Let's leave that for when it's actually needed.
